### ISSUE TITLE
default super user missing from dump?

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/disaster-asset-manager#11]
started mongodb running and then used 
`mongorestore -d arc_assets /Users/danbjoseph/Documents/Github/AmericanRedCross/disaster-asset-manager/dump/arc_assets`
tried to login with the default super user as described in the readme but it didn't work, logged in with credentials sent previously and it did, don't see the default super user in the list of users
<img width="813" alt="screen shot 2015-07-05 at 3 18 12 pm" src="https://cloud.githubusercontent.com/assets/4806884/8513013/5c94c20a-2329-11e5-98af-227c28e1dd52.png">

**Comment by kevinlustig** [comment]
You do not need to do a restore of the Mongo DB when installing on the V2
branch. The default super user will only be created if the user collection
is empty or doesn't exist. The thinking there is that if you have a user
table to restore, you probably don't need a default super user.

**Comment by danbjoseph** [comment]
got it :thumbsup:
