### ISSUE TITLE
modal needs focus on call

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/disaster-asset-manager#12]
if you click create asset and then try and scroll down the modal, it doesn't work. you have to click somewhere on it first. i think you should be able to scroll without having to click.

might not be a universal thing, I'm using:
Chrome Version 43.0.2357.132 (64-bit) on OSX 10.10.4

**Comment by kevinlustig** [comment]
This is Bootstrap modal default behavior, but I could add a script tweak to give focus to the modal.

**Comment by danbjoseph** [comment]
not a concern for v0.1

**Comment by kevinlustig** [comment]
Actually, I'm not seeing this anymore. I didn't make any changes, but the modal scrolls immediately for me. Tested in Chrome, FF, IE 10/11.
