### ISSUE TITLE
display eccentricity with resize of text input in modal

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/disaster-asset-manager#15]
re-sizeable text input box can be re-sized larger than the modal. (not a concern, just curious behavior)

![screen shot 2015-07-13 at 2 23 38 pm](https://cloud.githubusercontent.com/assets/4806884/8657331/07563e98-296b-11e5-983e-ef55e43a9908.png)

**Comment by kevinlustig** [comment]
Just needed a max-width. All set.
