### ISSUE TITLE
"document date" metadata

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/disaster-asset-manager#19]
- please continue to auto-record the upload date but also have the user input the document date / date of publication
- e.g. if a map of distributions as of June 16 is uploaded on June 18 because the person responsible is slow on their game
  - the June 16 date is more important to me for when interacting with document end-users
  - as an admin i want to know when maps are making it into the manager

**Comment by kevinlustig** [comment]
Assets now have a "createDate" property that is set automatically on creating, and a "date" property that is set by the user using the Create Asset/Edit Asset modals.
