### ISSUE TITLE
logos should be limited or configurable or something

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/disaster-asset-manager#21]
- not a priority. 
- make logo(s) configurable somehow? just stick with IFRC, AmCross, BritRC?
- the asset end-user access points will be appropriately branded, and that's whats important.
- Nepal RC logo will (hopefully) not be on the page next time we spin this up (they could use a break).
- IFRC logo should stay.
- American Red Cross and British Red Cross are the two biggest contributors to the SIMS (Surge Information Management Support) mechanism that makes a lot the maps and things. sometimes other people help out (e.g. Netherlands RC, Australian RC) with some things...
- what if it's a multi-country crisis? (e.g. we spin up an instance for something like ebola and want just one asset manager for Liberia, Sierra Leone, etc.)

**Comment by danbjoseph** [comment]
or just add a comment to the readme telling the person setting the instance up to edit the html in main.handlebars and put any necessary logos in the media folder

**Comment by kevinlustig** [comment]
Okay, logos are now handled automatically by being included in the /client/media/logos directory. I've added some more information on this to the README.
