### ISSUE TITLE
map for adding location doesn't always load

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/disaster-asset-manager#24]
sometimes the map doesn't load in the asset modal. will document the problem better and update this issue when I have some details to provide.

**Comment by kevinlustig** [comment]
The map has to be initialized after it is fully visible in the modal, or else Leaflet doesn't know how to handle its tiles properly. This should be controlled by the Bootstrap modal's "shown" event, but it seems like occasionally the timing doesn't work out. I've put a check into the geo stuff init function to check if the map container is visible. If not, it waits a small timeout (100 ms) and then tries to initialize again. This is ready to test, and will hopefully resolve the issue.
