### ISSUE TITLE
greater configurability for tag(s)?

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/disaster-asset-manager#25]
would it be possible to build the tag(s) interactively from the config.js asset_opts object? not just the lists of values but the keys as well? for example if you only had the `extents: [extent1,2,3]` then the asset modal would only have that one box. you could also add additional `key: [value array]` for more tags?

(I see that the variable for the assetSchema has 'extent' and 'sector' keys, so it's not just a user interface thing.)

**Comment by kevinlustig** [comment]
So if I understand right, you'd like to be able to define sets of tags
other than "Extent" and "Sector" via config.js? If that's correct, that's
definitely doable.

On Fri, Jul 31, 2015, 4:12 PM Dan Joseph notifications@github.com wrote:

> would it be possible to build the tag(s) interactively from the config.js
> asset_opts object? not just the lists of values but the keys as well? for
> example if you only had the extents: [extent1,2,3] then the asset modal
> would only have that one box. you could also add additional key: [value
> array] for more tags?
> 
> (I see that the variable for the assetSchema has 'extent' and 'sector'
> keys, so it's not just a user interface thing.)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AmericanRedCross/disaster-asset-manager/issues/25.
> 
> ## 
> 
> Kevin Lustig
> Founder, Developer
> The Journey Lab

+1 (202) 486-9684
kevin@thejourneylab.com
www.thejourneylab.com

**Comment by danbjoseph** [comment]
:+1:

**Comment by kevinlustig** [comment]
Tags are now controlled fully from config.js. Each set of tags is a property in the "tags" object under "asset_opts." Tag sets have a "required" boolean value to indicate whether or not the data schema should require at least one value for that field, and then a "values" array with all of the text values for individual tags. I will update the Readme to discuss this new structure.
