### ISSUE TITLE
button thing (UI/UX)

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/disaster-asset-manager#26]
With the create asset button the background changes color (making me think it's clickable) before the cursor is actually over the clickable portion of the button. The cursor does change appropriately.

![screen shot 2015-07-31 at 4 28 59 pm](https://cloud.githubusercontent.com/assets/4806884/9016737/4b1ff0e4-37a1-11e5-880c-2bb560bf656d.png)

![hover1](https://cloud.githubusercontent.com/assets/4806884/9016644/a99752ee-37a0-11e5-9ae3-3f32da0d935a.jpg)
![hover2](https://cloud.githubusercontent.com/assets/4806884/9016676/de6eae68-37a0-11e5-9749-5d2a0073cc1f.jpg)

**Comment by kevinlustig** [comment]
Good catch - the classic li:hover containing a smaller a tag. Careless.
I'll fix.

On Fri, Jul 31, 2015, 4:30 PM Dan Joseph notifications@github.com wrote:

> With the create asset button the background changes color (making me think
> it's clickable) before the cursor is actually over the clickable portion of
> the button. The cursor does change appropriately.
> 
> [image: screen shot 2015-07-31 at 4 28 59 pm]
> https://cloud.githubusercontent.com/assets/4806884/9016737/4b1ff0e4-37a1-11e5-880c-2bb560bf656d.png
> 
> [image: hover1]
> https://cloud.githubusercontent.com/assets/4806884/9016644/a99752ee-37a0-11e5-9ae3-3f32da0d935a.jpg
> [image: hover2]
> https://cloud.githubusercontent.com/assets/4806884/9016676/de6eae68-37a0-11e5-9749-5d2a0073cc1f.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AmericanRedCross/disaster-asset-manager/issues/26.
> 
> ## 
> 
> Kevin Lustig
> Founder, Developer
> The Journey Lab

+1 (202) 486-9684
kevin@thejourneylab.com
www.thejourneylab.com
