### ISSUE TITLE
auto generate centroid for map

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/disaster-asset-manager#5]
connect to geoforce for admin units and then use the selected hierarchies to attach centroid

**Comment by kevinlustig** [comment]
Can you provide some additional information on geoforce and any API or other methods I should be using to get the admin units? I've seen the Github project, but if you can shortcut me on how you want me to integrate here, that would be helpful.

Also, assuming the centroid of the asset is just the centroid of the relevant extent - what about assets with multiple extents?

**Comment by danbjoseph** [comment]
@dalekunce:

> basically we want a user to search for their place and have the entire admin stack added to the uploaded object. On the map we can then aggregate assets at any admin level. The site currently will provide a json of the stack so it just needs to be added in.  
> I think having a map as an alternative that will feed an x/y to the search tool to get the stack would be helpful as well.

https://github.com/AmericanRedCross/GeoWebServices/blob/master/queryingGeoServices.md#sample-results-1

my only issue with this is that if people are searching they might be using an alternate spelling or searching for an admin unit smaller than what we have (e.g. a village or settlement) and it will be tough to guide/train them to work backwards up the admin stack in their search queries until they find a match

i think it would be faster and easier if we could have them click down through the admin stack, selecting units that we have in our data, until there is no obvious match. this way we can leverage their (hopefully) human-level recognition skills to make close-but-not-quite-the-same-spelling matches etc during a few cascading select type choices.

**Comment by danbjoseph** [comment]
- for multiple extents, i think we just have them stop at the broadest admin level. 
- for example, if the map is of 2 municipalities in a province with 5 total municipalities, we just have them tag it with the province.
- in some cases the "extent" will potentially be not very descriptive (e.g. if a map covered the eastern half of Nepal, two or three  [regions](https://en.wikipedia.org/wiki/Development_regions_of_Nepal), then you'd probably just end up tagging it 'Nepal')
- but i'm not sure the potential increased detail in some cases outweighs the increase in complexity in the metadata and in the tagging process when the user is uploading a document
- i'm open to ideas or the argument that it could be implemented efficiently (on the front and back end)

**Comment by kevinlustig** [comment]
Couple of thoughts - one, it will be interesting to get the regions actually plugged in and see how it looks. It might be simple to scan, or a simple text search might be helpful. Let me get the drill-down set up in a basic way, and then we can see what tools we need to make it more usable. 

Two, regarding multiple centroids, from the UX perspective is the primary point of the thumbnails on the map "These are the maps we have for this area," or is it "This is the area that is relevant for this map."? If it's the former, it might make sense to show a reference for each map in each area that's relevant to the map. My thinking here is just that if a user is looking at a region and wondering about maps available for that region, it would probably benefit them to see all relevant maps there, even if those maps also happen to be relevant for other regions. It wouldn't be difficult to give each map a list of centroids, one for each of the regions that are covered. 

But, if each map needs to have one "official" centroid, the suggestions you've made here make a lot of sense for identifying which centroid that should be.
